name: blog deploy
on:
  push:
    tags:
      - '*'
    branches: [ main ]
permissions:
  contents: write
 
env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build:
        runs-on: ubuntu-latest
        concurrency:
            group: ${{ github.workflow }} - ${{ github.ref }}
        steps:
            - name: checkout
              uses: actions/checkout@v4
              with:
                submodules: true
                fetch-depth: 0
                
            - name: setup hugo
              uses: peaceiris/actions-hugo@v3
              with:
                hugo-version: '0.124.1'
                extended: true
                
            - name: build
              run: hugo --minify --config hugo.yaml
            
            - name: deploy
              uses: peaceiris/actions-gh-pages@v3
              if: ${{ github.ref == 'refs/heads/main' }}
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./docs
            - name: cache Hugo resources
              uses: actions/cache@v3
              with:
                path: resources
                key: ${{ runner.os }}-hugo-resources-${{ github.sha }}
